import type { Metadata } from "next";
import { Neuton, Nunito_Sans, Noto_Serif } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import Nav from "@/components/Nav";
/* import localFont from "next/font/local"; */

const primary = Nunito_Sans({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-primary",
  weight: ["400", "500", "600", "700", "800"],
});

const secondary = Noto_Serif({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  variable: "--font-secondary",
  weight: ["400", "500", "600", "700", "800"],
});

/* const primary = localFont({
  src: [
    {
      path: "../public/fonts/LibertinusSans-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/LibertinusSans-Italic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/LibertinusSans-Bold.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  variable: "--font-primary",
  display: "swap",
}); */

/* const fraunces = Gabriela({
  subsets: ["latin"],
  style: ["normal"],
  display: "swap",
  weight: "400",
  variable: "--font-secondary",
}); */

export const title = Neuton({
  subsets: ["latin"],
  style: ["normal", "italic"],
  display: "swap",
  weight: ["400", "700", "800"],
  variable: "--font-title",
});

export const metadata: Metadata = {
  title: "Tarot",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${title.variable} ${primary.variable} ${secondary.variable}
        relative lg:pl-12 antialiased`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
